-- FutureCrime Summit 2026 — agenda seed
-- Generated from FCS_Speaker_and_Sessions_28th_july_(Revised).xlsx + FCRF_Track_2.docx
-- Main Hall: full detail. Innovation Hall: Track 2 structure only, speakers pending.
-- Contact numbers and internal remarks intentionally excluded.

SET NAMES utf8mb4;
START TRANSACTION;

INSERT INTO agenda_halls (name, venue, sort_order) VALUES
  ('Main Hall', 'Bharat Mandapam, Pragati Maidan, New Delhi', 1),
  ('Innovation Hall', 'Bharat Mandapam, Pragati Maidan, New Delhi', 2)
ON DUPLICATE KEY UPDATE venue = VALUES(venue);

SET @main = (SELECT id FROM agenda_halls WHERE name = 'Main Hall');
SET @innov = (SELECT id FROM agenda_halls WHERE name = 'Innovation Hall');

-- ---------- speakers ----------
INSERT INTO agenda_speakers (full_name, slug, designation, organisation, photo_path, status) VALUES ('Megha Khetarpal', 'megha-khetarpal', NULL, 'TransUnion', NULL, 'published') ON DUPLICATE KEY UPDATE designation = VALUES(designation);
INSERT INTO agenda_speakers (full_name, slug, designation, organisation, photo_path, status) VALUES ('Mini Rani Sharma', 'mini-rani-sharma', NULL, 'Head SeMT, MeiTY', NULL, 'published') ON DUPLICATE KEY UPDATE designation = VALUES(designation);
INSERT INTO agenda_speakers (full_name, slug, designation, organisation, photo_path, status) VALUES ('Air Vice Marshal (Dr) Devesh Vatsa VSM', 'air-vice-marshal-dr-devesh-vatsa-vsm', NULL, 'Advisor, DSCI NASSCOM', NULL, 'published') ON DUPLICATE KEY UPDATE designation = VALUES(designation);
INSERT INTO agenda_speakers (full_name, slug, designation, organisation, photo_path, status) VALUES ('Somen das', 'somen-das', 'Associate director', 'Accenture Cybersecurity', NULL, 'published') ON DUPLICATE KEY UPDATE designation = VALUES(designation);
INSERT INTO agenda_speakers (full_name, slug, designation, organisation, photo_path, status) VALUES ('Lt. Col. Nishant Singh', 'lt-col-nishant-singh', NULL, 'GRAMAX', NULL, 'published') ON DUPLICATE KEY UPDATE designation = VALUES(designation);
INSERT INTO agenda_speakers (full_name, slug, designation, organisation, photo_path, status) VALUES ('Naveen Jhakar', 'naveen-jhakar', NULL, 'ITS', NULL, 'published') ON DUPLICATE KEY UPDATE designation = VALUES(designation);
INSERT INTO agenda_speakers (full_name, slug, designation, organisation, photo_path, status) VALUES ('Dinesh O Bareja', 'dinesh-o-bareja', NULL, 'Cybersecurity Consultant', NULL, 'published') ON DUPLICATE KEY UPDATE designation = VALUES(designation);
INSERT INTO agenda_speakers (full_name, slug, designation, organisation, photo_path, status) VALUES ('Ashutosh Bahuguna', 'ashutosh-bahuguna', NULL, 'Cert-IN', NULL, 'published') ON DUPLICATE KEY UPDATE designation = VALUES(designation);
INSERT INTO agenda_speakers (full_name, slug, designation, organisation, photo_path, status) VALUES ('Prof. (Dr.) Deepak Singh', 'prof-dr-deepak-singh', 'Associate Prof.', 'IIIT, Lko', NULL, 'published') ON DUPLICATE KEY UPDATE designation = VALUES(designation);
INSERT INTO agenda_speakers (full_name, slug, designation, organisation, photo_path, status) VALUES ('Preeti Singh', 'preeti-singh', NULL, 'Group CISO at Teciem', NULL, 'published') ON DUPLICATE KEY UPDATE designation = VALUES(designation);
INSERT INTO agenda_speakers (full_name, slug, designation, organisation, photo_path, status) VALUES ('Dr. Rakshit Tandon', 'dr-rakshit-tandon', 'Consultant', 'Cyber Crime HQ UP Police International Cyber Expert', NULL, 'published') ON DUPLICATE KEY UPDATE designation = VALUES(designation);
INSERT INTO agenda_speakers (full_name, slug, designation, organisation, photo_path, status) VALUES ('Ramkumari Iyer', 'ramkumari-iyer', 'CIO & AI Security Governance director', 'Reliscale consulting pvt ltd.', NULL, 'published') ON DUPLICATE KEY UPDATE designation = VALUES(designation);
INSERT INTO agenda_speakers (full_name, slug, designation, organisation, photo_path, status) VALUES ('Shishir Sarkar', 'shishir-sarkar', 'Enterprise architect', 'vice president, DEUTSCHE BANK', NULL, 'published') ON DUPLICATE KEY UPDATE designation = VALUES(designation);
INSERT INTO agenda_speakers (full_name, slug, designation, organisation, photo_path, status) VALUES ('Deepak Vatsa', 'deepak-vatsa', NULL, 'HDFC ERGO', NULL, 'draft') ON DUPLICATE KEY UPDATE designation = VALUES(designation);
INSERT INTO agenda_speakers (full_name, slug, designation, organisation, photo_path, status) VALUES ('CA Bharat Jeswani', 'ca-bharat-jeswani', 'FCA', 'CFE, CFCS, CAMS- Founder AML Consultancy', NULL, 'published') ON DUPLICATE KEY UPDATE designation = VALUES(designation);
INSERT INTO agenda_speakers (full_name, slug, designation, organisation, photo_path, status) VALUES ('CA Durgesh Pandey', 'ca-durgesh-pandey', 'Managing Partner of my Firm DKMS and Associates and Honorary Professor', 'University of Portsmouth, UK', NULL, 'published') ON DUPLICATE KEY UPDATE designation = VALUES(designation);
INSERT INTO agenda_speakers (full_name, slug, designation, organisation, photo_path, status) VALUES ('CA Uday Kulkarni', 'ca-uday-kulkarni', NULL, 'PRACTICING CHARTERED ACCOUNTANT', NULL, 'published') ON DUPLICATE KEY UPDATE designation = VALUES(designation);
INSERT INTO agenda_speakers (full_name, slug, designation, organisation, photo_path, status) VALUES ('Mr. Gyan Barah', 'mr-gyan-barah', 'Senior Advisor', 'JIO Financial Services', NULL, 'published') ON DUPLICATE KEY UPDATE designation = VALUES(designation);
INSERT INTO agenda_speakers (full_name, slug, designation, organisation, photo_path, status) VALUES ('Soham Shah', 'soham-shah', 'Founder and CEO', 'Yellow Stone Solutions', NULL, 'draft') ON DUPLICATE KEY UPDATE designation = VALUES(designation);
INSERT INTO agenda_speakers (full_name, slug, designation, organisation, photo_path, status) VALUES ('Dubashish', 'dubashish', NULL, 'HDFC', NULL, 'draft') ON DUPLICATE KEY UPDATE designation = VALUES(designation);
INSERT INTO agenda_speakers (full_name, slug, designation, organisation, photo_path, status) VALUES ('Aman Bandvi', 'aman-bandvi', 'Founder', 'Director- Bharat Responsible AI Forum', NULL, 'published') ON DUPLICATE KEY UPDATE designation = VALUES(designation);
INSERT INTO agenda_speakers (full_name, slug, designation, organisation, photo_path, status) VALUES ('Piyush Kaushik', 'piyush-kaushik', 'Product manager forensics', 'Exterro', NULL, 'published') ON DUPLICATE KEY UPDATE designation = VALUES(designation);
INSERT INTO agenda_speakers (full_name, slug, designation, organisation, photo_path, status) VALUES ('mFilterIt', 'mfilterit', NULL, NULL, NULL, 'draft') ON DUPLICATE KEY UPDATE designation = VALUES(designation);
INSERT INTO agenda_speakers (full_name, slug, designation, organisation, photo_path, status) VALUES ('Jignesh suba', 'jignesh-suba', NULL, 'mH Service', NULL, 'draft') ON DUPLICATE KEY UPDATE designation = VALUES(designation);
INSERT INTO agenda_speakers (full_name, slug, designation, organisation, photo_path, status) VALUES ('Abhinav Saurabh', 'abhinav-saurabh', 'Strategic Advisor', 'Confidential', NULL, 'draft') ON DUPLICATE KEY UPDATE designation = VALUES(designation);
INSERT INTO agenda_speakers (full_name, slug, designation, organisation, photo_path, status) VALUES ('Alok Gupta', 'alok-gupta', NULL, NULL, NULL, 'draft') ON DUPLICATE KEY UPDATE designation = VALUES(designation);
INSERT INTO agenda_speakers (full_name, slug, designation, organisation, photo_path, status) VALUES ('Starlight', 'starlight', NULL, NULL, NULL, 'draft') ON DUPLICATE KEY UPDATE designation = VALUES(designation);
INSERT INTO agenda_speakers (full_name, slug, designation, organisation, photo_path, status) VALUES ('Innefu', 'innefu', NULL, NULL, NULL, 'draft') ON DUPLICATE KEY UPDATE designation = VALUES(designation);
INSERT INTO agenda_speakers (full_name, slug, designation, organisation, photo_path, status) VALUES ('Kumar Aniket', 'kumar-aniket', NULL, NULL, NULL, 'draft') ON DUPLICATE KEY UPDATE designation = VALUES(designation);
INSERT INTO agenda_speakers (full_name, slug, designation, organisation, photo_path, status) VALUES ('Sainath Volam', 'sainath-volam', NULL, NULL, NULL, 'draft') ON DUPLICATE KEY UPDATE designation = VALUES(designation);
INSERT INTO agenda_speakers (full_name, slug, designation, organisation, photo_path, status) VALUES ('Ajay Kanth ABC', 'ajay-kanth-abc', NULL, NULL, NULL, 'draft') ON DUPLICATE KEY UPDATE designation = VALUES(designation);
INSERT INTO agenda_speakers (full_name, slug, designation, organisation, photo_path, status) VALUES ('Dr.Navaneethan M', 'dr-navaneethan-m', NULL, 'Chairman of CXO Cywayz', NULL, 'draft') ON DUPLICATE KEY UPDATE designation = VALUES(designation);
INSERT INTO agenda_speakers (full_name, slug, designation, organisation, photo_path, status) VALUES ('Sanjay Kaushik', 'sanjay-kaushik', NULL, NULL, NULL, 'draft') ON DUPLICATE KEY UPDATE designation = VALUES(designation);
INSERT INTO agenda_speakers (full_name, slug, designation, organisation, photo_path, status) VALUES ('Bharat Panchal', 'bharat-panchal', NULL, NULL, NULL, 'draft') ON DUPLICATE KEY UPDATE designation = VALUES(designation);
INSERT INTO agenda_speakers (full_name, slug, designation, organisation, photo_path, status) VALUES ('Major General Dr Rajan Kochhar, VSM', 'major-general-dr-rajan-kochhar-vsm', NULL, 'Alok Vijayant', NULL, 'draft') ON DUPLICATE KEY UPDATE designation = VALUES(designation);
INSERT INTO agenda_speakers (full_name, slug, designation, organisation, photo_path, status) VALUES ('Gulshan Rai', 'gulshan-rai', NULL, 'Pavan duggal', NULL, 'draft') ON DUPLICATE KEY UPDATE designation = VALUES(designation);
INSERT INTO agenda_speakers (full_name, slug, designation, organisation, photo_path, status) VALUES ('Rakesh Maheshwari', 'rakesh-maheshwari', NULL, NULL, NULL, 'draft') ON DUPLICATE KEY UPDATE designation = VALUES(designation);
INSERT INTO agenda_speakers (full_name, slug, designation, organisation, photo_path, status) VALUES ('Arun Kumar', 'arun-kumar', NULL, NULL, NULL, 'draft') ON DUPLICATE KEY UPDATE designation = VALUES(designation);
INSERT INTO agenda_speakers (full_name, slug, designation, organisation, photo_path, status) VALUES ('Amit Sharma DRDO', 'amit-sharma-drdo', NULL, NULL, NULL, 'draft') ON DUPLICATE KEY UPDATE designation = VALUES(designation);
INSERT INTO agenda_speakers (full_name, slug, designation, organisation, photo_path, status) VALUES ('Devesh Vatsa', 'devesh-vatsa', NULL, NULL, NULL, 'draft') ON DUPLICATE KEY UPDATE designation = VALUES(designation);
INSERT INTO agenda_speakers (full_name, slug, designation, organisation, photo_path, status) VALUES ('Balaji Kapsikar', 'balaji-kapsikar', NULL, NULL, NULL, 'published') ON DUPLICATE KEY UPDATE designation = VALUES(designation);
INSERT INTO agenda_speakers (full_name, slug, designation, organisation, photo_path, status) VALUES ('Utsav Mittal', 'utsav-mittal', NULL, NULL, NULL, 'draft') ON DUPLICATE KEY UPDATE designation = VALUES(designation);
INSERT INTO agenda_speakers (full_name, slug, designation, organisation, photo_path, status) VALUES ('QnU Labs', 'qnu-labs', NULL, NULL, NULL, 'draft') ON DUPLICATE KEY UPDATE designation = VALUES(designation);
INSERT INTO agenda_speakers (full_name, slug, designation, organisation, photo_path, status) VALUES ('Amit Dubey', 'amit-dubey', NULL, NULL, NULL, 'draft') ON DUPLICATE KEY UPDATE designation = VALUES(designation);
INSERT INTO agenda_speakers (full_name, slug, designation, organisation, photo_path, status) VALUES ('Smith & company', 'smith-company', NULL, NULL, NULL, 'draft') ON DUPLICATE KEY UPDATE designation = VALUES(designation);
INSERT INTO agenda_speakers (full_name, slug, designation, organisation, photo_path, status) VALUES ('Ms. Paakhhi Garg', 'ms-paakhhi-garg', 'Founder', 'World Cybersecurity Forum', NULL, 'published') ON DUPLICATE KEY UPDATE designation = VALUES(designation);
INSERT INTO agenda_speakers (full_name, slug, designation, organisation, photo_path, status) VALUES ('Ms. Garima Goswamy', 'ms-garima-goswamy', 'Principal risk advisor', 'Inquest Global', NULL, 'published') ON DUPLICATE KEY UPDATE designation = VALUES(designation);
INSERT INTO agenda_speakers (full_name, slug, designation, organisation, photo_path, status) VALUES ('Sampurna', 'sampurna', NULL, NULL, NULL, 'published') ON DUPLICATE KEY UPDATE designation = VALUES(designation);
INSERT INTO agenda_speakers (full_name, slug, designation, organisation, photo_path, status) VALUES ('Tanmayee Tilekar', 'tanmayee-tilekar', NULL, 'Cybersecurity Expert', NULL, 'published') ON DUPLICATE KEY UPDATE designation = VALUES(designation);
INSERT INTO agenda_speakers (full_name, slug, designation, organisation, photo_path, status) VALUES ('Smita Mitra', 'smita-mitra', NULL, 'INTERPOL, UN', NULL, 'published') ON DUPLICATE KEY UPDATE designation = VALUES(designation);
INSERT INTO agenda_speakers (full_name, slug, designation, organisation, photo_path, status) VALUES ('Shonal D', 'shonal-d', 'Anti-Cybercrime Strategist', 'AI & Cyber Psychologist', NULL, 'published') ON DUPLICATE KEY UPDATE designation = VALUES(designation);
INSERT INTO agenda_speakers (full_name, slug, designation, organisation, photo_path, status) VALUES ('Mimansa Ambastha', 'mimansa-ambastha', 'Founder', 'Starlex consultancy', NULL, 'published') ON DUPLICATE KEY UPDATE designation = VALUES(designation);
INSERT INTO agenda_speakers (full_name, slug, designation, organisation, photo_path, status) VALUES ('Mr. Divyam Aggarwal', 'mr-divyam-aggarwal', NULL, 'JSA', NULL, 'published') ON DUPLICATE KEY UPDATE designation = VALUES(designation);
INSERT INTO agenda_speakers (full_name, slug, designation, organisation, photo_path, status) VALUES ('Suditi Tandon', 'suditi-tandon', NULL, 'Forvia Hella', NULL, 'published') ON DUPLICATE KEY UPDATE designation = VALUES(designation);
INSERT INTO agenda_speakers (full_name, slug, designation, organisation, photo_path, status) VALUES ('Mahak Rathee', 'mahak-rathee', 'Advocate on Record', 'Supreme Court', NULL, 'published') ON DUPLICATE KEY UPDATE designation = VALUES(designation);
INSERT INTO agenda_speakers (full_name, slug, designation, organisation, photo_path, status) VALUES ('Krishan Kumar', 'krishan-kumar', 'Associate VP& Senior Legal Counsel', 'Al & Data Security', NULL, 'draft') ON DUPLICATE KEY UPDATE designation = VALUES(designation);
INSERT INTO agenda_speakers (full_name, slug, designation, organisation, photo_path, status) VALUES ('Vibhav Mittal', 'vibhav-mittal', NULL, 'Anand and Anand', NULL, 'draft') ON DUPLICATE KEY UPDATE designation = VALUES(designation);
INSERT INTO agenda_speakers (full_name, slug, designation, organisation, photo_path, status) VALUES ('Kulbhhushan Upadhyay', 'kulbhhushan-upadhyay', 'Assistant General Manager', 'Telecommunications Consultants India Ltd', NULL, 'published') ON DUPLICATE KEY UPDATE designation = VALUES(designation);

-- ---------- sessions ----------
INSERT INTO agenda_sessions (day_id, hall_id, title, session_type, start_time, end_time, sort_order, status, external_ref) VALUES (1, @main, 'Modern Cyber Policing Framework: Reimagining Central and State Law Enforcement in the AI Age', 'inauguration', '09:30:00', '11:00:00', 10, 'published', 'INAUG-D1');
INSERT INTO agenda_sessions (day_id, hall_id, title, session_type, start_time, end_time, sort_order, status, external_ref) VALUES (1, @innov, 'AI in Policing: Live Use Cases and AI-Powered Investigation Platforms', 'workshop', '10:30:00', '11:00:00', 20, 'draft', 'TRACK2');
INSERT INTO agenda_sessions (day_id, hall_id, title, session_type, start_time, end_time, sort_order, status, external_ref) VALUES (1, @main, 'Crime at Machine Speed: AI-Powered Cybercrime and the New Threat Landscape', 'panel', '11:00:00', '11:40:00', 30, 'published', 'Panel 1');
INSERT INTO agenda_sessions (day_id, hall_id, title, session_type, start_time, end_time, sort_order, status, external_ref) VALUES (1, @innov, 'SOC for LEAs: Building a Next-Generation Security Operations Centre', 'workshop', '11:00:00', '11:30:00', 40, 'draft', 'TRACK2');
INSERT INTO agenda_sessions (day_id, hall_id, title, session_type, start_time, end_time, sort_order, status, external_ref) VALUES (1, @innov, 'Sponsor Innovation Showcase 1', 'other', '11:30:00', '12:25:00', 50, 'draft', 'TRACK2');
INSERT INTO agenda_sessions (day_id, hall_id, title, session_type, start_time, end_time, sort_order, status, external_ref) VALUES (1, @main, 'Sponsor Session 1', 'other', '11:40:00', '12:00:00', 60, 'published', NULL);
INSERT INTO agenda_sessions (day_id, hall_id, title, session_type, start_time, end_time, sort_order, status, external_ref) VALUES (1, @main, 'Defending the Digital Backbone: AI, Critical Infrastructure and Cyber Resilience', 'panel', '12:00:00', '12:40:00', 70, 'published', 'Panel 2');
INSERT INTO agenda_sessions (day_id, hall_id, title, session_type, start_time, end_time, sort_order, status, external_ref) VALUES (1, @innov, 'Cyber Lab Creation: From Planning to Operational Readiness', 'workshop', '12:25:00', '12:55:00', 80, 'draft', 'TRACK2');
INSERT INTO agenda_sessions (day_id, hall_id, title, session_type, start_time, end_time, sort_order, status, external_ref) VALUES (1, @main, 'Sponsor Session 2', 'other', '12:40:00', '13:00:00', 90, 'published', NULL);
INSERT INTO agenda_sessions (day_id, hall_id, title, session_type, start_time, end_time, sort_order, status, external_ref) VALUES (1, NULL, 'Lunch Break', 'lunch', '13:00:00', '14:00:00', 100, 'published', NULL);
INSERT INTO agenda_sessions (day_id, hall_id, title, session_type, start_time, end_time, sort_order, status, external_ref) VALUES (1, @main, 'Beyond Secure Banking: Cybersecurity, Digital Payments and the Future of Financial Fraud Prevention', 'panel', '14:00:00', '14:40:00', 110, 'published', 'Panel 3');
INSERT INTO agenda_sessions (day_id, hall_id, title, session_type, start_time, end_time, sort_order, status, external_ref) VALUES (1, @innov, 'Drone Forensics: Evidence Acquisition, Preservation and Analysis', 'workshop', '14:00:00', '14:30:00', 120, 'draft', 'TRACK2');
INSERT INTO agenda_sessions (day_id, hall_id, title, session_type, start_time, end_time, sort_order, status, external_ref) VALUES (1, @innov, 'Sponsor Innovation Showcase 2', 'other', '14:30:00', '15:10:00', 130, 'draft', 'TRACK2');
INSERT INTO agenda_sessions (day_id, hall_id, title, session_type, start_time, end_time, sort_order, status, external_ref) VALUES (1, @main, 'Follow the Money: Crypto Fraud, Financial Crime and AML/CFT Intelligence', 'panel', '14:40:00', '15:20:00', 140, 'published', 'Panel 4');
INSERT INTO agenda_sessions (day_id, hall_id, title, session_type, start_time, end_time, sort_order, status, external_ref) VALUES (1, @innov, 'Tea and Networking Break', 'break', '15:10:00', '15:25:00', 150, 'draft', 'TRACK2');
INSERT INTO agenda_sessions (day_id, hall_id, title, session_type, start_time, end_time, sort_order, status, external_ref) VALUES (1, @main, 'From Data to Action: Predictive Policing, OSINT, Dark Web and AI-Led Investigation', 'panel', '15:20:00', '16:00:00', 160, 'published', 'Panel 5');
INSERT INTO agenda_sessions (day_id, hall_id, title, session_type, start_time, end_time, sort_order, status, external_ref) VALUES (1, @innov, 'Consent Management Platform under the DPDP Act: Live Demonstration', 'workshop', '15:25:00', '15:55:00', 170, 'draft', 'TRACK2');
INSERT INTO agenda_sessions (day_id, hall_id, title, session_type, start_time, end_time, sort_order, status, external_ref) VALUES (1, @innov, 'Innovation Zone Walkthrough, Live Demonstrations and Sponsor Networking', 'networking', '15:55:00', '16:30:00', 180, 'draft', 'TRACK2');
INSERT INTO agenda_sessions (day_id, hall_id, title, session_type, start_time, end_time, sort_order, status, external_ref) VALUES (1, @innov, 'AI-Powered Digital Forensics: Transforming Evidence Analysis and Criminal Investigation', 'panel', '16:00:00', '16:40:00', 190, 'draft', 'Panel 6');
INSERT INTO agenda_sessions (day_id, hall_id, title, session_type, start_time, end_time, sort_order, status, external_ref) VALUES (1, @innov, 'The Cyber Compliance Mandate: Aligning Security Audits with RBI, SEBI and CERT-In Requirements', 'panel', '16:40:00', '17:20:00', 200, 'draft', 'Panel 7');
INSERT INTO agenda_sessions (day_id, hall_id, title, session_type, start_time, end_time, sort_order, status, external_ref) VALUES (2, @main, 'The New Theatre of Conflict: Cyber Warfare, Geopolitical Rivalries and National Security', 'panel', '09:30:00', '11:00:00', 10, 'published', 'Panel 8');
INSERT INTO agenda_sessions (day_id, hall_id, title, session_type, start_time, end_time, sort_order, status, external_ref) VALUES (2, @innov, 'Cyber Range for Cyber Commandos: Live Attack-and-Defence Simulation', 'workshop', '10:30:00', '11:00:00', 20, 'draft', 'TRACK2');
INSERT INTO agenda_sessions (day_id, hall_id, title, session_type, start_time, end_time, sort_order, status, external_ref) VALUES (2, @main, 'Beyond Encryption: Quantum-Safe Security and Future Tech-Crimes', 'panel', '11:00:00', '11:40:00', 30, 'published', 'Panel 9');
INSERT INTO agenda_sessions (day_id, hall_id, title, session_type, start_time, end_time, sort_order, status, external_ref) VALUES (2, @innov, 'Sponsor Innovation Showcase 3', 'other', '11:00:00', '11:40:00', 40, 'draft', 'TRACK2');
INSERT INTO agenda_sessions (day_id, hall_id, title, session_type, start_time, end_time, sort_order, status, external_ref) VALUES (2, @innov, 'Digital Evidence Without Borders: Tackling Cross-Border Cybercrime Through International Cooperation', 'panel', '11:40:00', '12:20:00', 50, 'draft', 'Panel 10');
INSERT INTO agenda_sessions (day_id, hall_id, title, session_type, start_time, end_time, sort_order, status, external_ref) VALUES (2, @innov, 'Tea and Networking Break', 'break', '11:40:00', '11:55:00', 60, 'draft', 'TRACK2');
INSERT INTO agenda_sessions (day_id, hall_id, title, session_type, start_time, end_time, sort_order, status, external_ref) VALUES (2, @innov, 'TTEX – Cyber Crisis Exercise: Command, Coordination and Response Drill', 'workshop', '11:55:00', '12:25:00', 70, 'draft', 'TRACK2');
INSERT INTO agenda_sessions (day_id, hall_id, title, session_type, start_time, end_time, sort_order, status, external_ref) VALUES (2, @main, 'Sponsor Slot', 'other', '12:20:00', '13:00:00', 80, 'published', NULL);
INSERT INTO agenda_sessions (day_id, hall_id, title, session_type, start_time, end_time, sort_order, status, external_ref) VALUES (2, @innov, 'Mobile and Cyber Forensics: Live Extraction and Evidence Analysis Demo', 'workshop', '12:25:00', '12:55:00', 90, 'draft', 'TRACK2');
INSERT INTO agenda_sessions (day_id, hall_id, title, session_type, start_time, end_time, sort_order, status, external_ref) VALUES (2, NULL, 'Lunch Break', 'lunch', '13:00:00', '14:00:00', 100, 'published', NULL);
INSERT INTO agenda_sessions (day_id, hall_id, title, session_type, start_time, end_time, sort_order, status, external_ref) VALUES (2, @main, 'Protecting the Vulnerable: Child Safety, Cyberstalking and Online Victim Protection & CSAM', 'panel', '14:00:00', '14:40:00', 110, 'published', 'Panel 11');
INSERT INTO agenda_sessions (day_id, hall_id, title, session_type, start_time, end_time, sort_order, status, external_ref) VALUES (2, @innov, 'Sponsor Innovation Showcase 4', 'other', '14:00:00', '14:40:00', 120, 'draft', 'TRACK2');
INSERT INTO agenda_sessions (day_id, hall_id, title, session_type, start_time, end_time, sort_order, status, external_ref) VALUES (2, @main, 'From Privacy to Responsible AI: DPDP Act Compliance, Data Protection and AI Governance', 'panel', '14:40:00', '15:20:00', 130, 'published', 'Panel 12');
INSERT INTO agenda_sessions (day_id, hall_id, title, session_type, start_time, end_time, sort_order, status, external_ref) VALUES (2, @innov, 'Deepfake Detection: Live Verification and Digital Evidence Workflow', 'panel', '14:40:00', '15:10:00', 140, 'draft', 'TRACK2');
INSERT INTO agenda_sessions (day_id, hall_id, title, session_type, start_time, end_time, sort_order, status, external_ref) VALUES (2, @innov, 'Sponsor Innovation Showcase 5', 'other', '15:10:00', '15:50:00', 150, 'draft', 'TRACK2');
INSERT INTO agenda_sessions (day_id, hall_id, title, session_type, start_time, end_time, sort_order, status, external_ref) VALUES (2, @main, 'The Next Evidence Frontier: Cloud, Drone, IoT, Vehicle and Location Forensics', 'panel', '15:20:00', '16:00:00', 160, 'published', 'Panel 13');
INSERT INTO agenda_sessions (day_id, hall_id, title, session_type, start_time, end_time, sort_order, status, external_ref) VALUES (2, @innov, 'Tea and Transition Break', 'break', '15:50:00', '16:00:00', 170, 'draft', 'TRACK2');
INSERT INTO agenda_sessions (day_id, hall_id, title, session_type, start_time, end_time, sort_order, status, external_ref) VALUES (2, @innov, 'Emerging Cyber Crimes, New Laws and Best Practices in Investigation', 'panel', '16:00:00', '16:30:00', 180, 'draft', 'TRACK2');

-- ---------- session <-> speaker ----------
INSERT IGNORE INTO agenda_session_speakers (session_id, speaker_id, speaker_role, sort_order) SELECT s.id, sp.id, 'panelist', 1 FROM agenda_sessions s, agenda_speakers sp WHERE s.external_ref = 'Panel 1' AND sp.slug = 'megha-khetarpal';
INSERT IGNORE INTO agenda_session_speakers (session_id, speaker_id, speaker_role, sort_order) SELECT s.id, sp.id, 'panelist', 2 FROM agenda_sessions s, agenda_speakers sp WHERE s.external_ref = 'Panel 1' AND sp.slug = 'mini-rani-sharma';
INSERT IGNORE INTO agenda_session_speakers (session_id, speaker_id, speaker_role, sort_order) SELECT s.id, sp.id, 'panelist', 3 FROM agenda_sessions s, agenda_speakers sp WHERE s.external_ref = 'Panel 1' AND sp.slug = 'air-vice-marshal-dr-devesh-vatsa-vsm';
INSERT IGNORE INTO agenda_session_speakers (session_id, speaker_id, speaker_role, sort_order) SELECT s.id, sp.id, 'panelist', 4 FROM agenda_sessions s, agenda_speakers sp WHERE s.external_ref = 'Panel 1' AND sp.slug = 'somen-das';
INSERT IGNORE INTO agenda_session_speakers (session_id, speaker_id, speaker_role, sort_order) SELECT s.id, sp.id, 'panelist', 1 FROM agenda_sessions s, agenda_speakers sp WHERE s.external_ref = 'Panel 2' AND sp.slug = 'lt-col-nishant-singh';
INSERT IGNORE INTO agenda_session_speakers (session_id, speaker_id, speaker_role, sort_order) SELECT s.id, sp.id, 'panelist', 2 FROM agenda_sessions s, agenda_speakers sp WHERE s.external_ref = 'Panel 2' AND sp.slug = 'naveen-jhakar';
INSERT IGNORE INTO agenda_session_speakers (session_id, speaker_id, speaker_role, sort_order) SELECT s.id, sp.id, 'panelist', 3 FROM agenda_sessions s, agenda_speakers sp WHERE s.external_ref = 'Panel 2' AND sp.slug = 'dinesh-o-bareja';
INSERT IGNORE INTO agenda_session_speakers (session_id, speaker_id, speaker_role, sort_order) SELECT s.id, sp.id, 'panelist', 4 FROM agenda_sessions s, agenda_speakers sp WHERE s.external_ref = 'Panel 2' AND sp.slug = 'ashutosh-bahuguna';
INSERT IGNORE INTO agenda_session_speakers (session_id, speaker_id, speaker_role, sort_order) SELECT s.id, sp.id, 'panelist', 5 FROM agenda_sessions s, agenda_speakers sp WHERE s.external_ref = 'Panel 2' AND sp.slug = 'prof-dr-deepak-singh';
INSERT IGNORE INTO agenda_session_speakers (session_id, speaker_id, speaker_role, sort_order) SELECT s.id, sp.id, 'panelist', 6 FROM agenda_sessions s, agenda_speakers sp WHERE s.external_ref = 'Panel 2' AND sp.slug = 'preeti-singh';
INSERT IGNORE INTO agenda_session_speakers (session_id, speaker_id, speaker_role, sort_order) SELECT s.id, sp.id, 'panelist', 1 FROM agenda_sessions s, agenda_speakers sp WHERE s.external_ref = 'Panel 3' AND sp.slug = 'dr-rakshit-tandon';
INSERT IGNORE INTO agenda_session_speakers (session_id, speaker_id, speaker_role, sort_order) SELECT s.id, sp.id, 'panelist', 2 FROM agenda_sessions s, agenda_speakers sp WHERE s.external_ref = 'Panel 3' AND sp.slug = 'ramkumari-iyer';
INSERT IGNORE INTO agenda_session_speakers (session_id, speaker_id, speaker_role, sort_order) SELECT s.id, sp.id, 'panelist', 3 FROM agenda_sessions s, agenda_speakers sp WHERE s.external_ref = 'Panel 3' AND sp.slug = 'shishir-sarkar';
INSERT IGNORE INTO agenda_session_speakers (session_id, speaker_id, speaker_role, sort_order) SELECT s.id, sp.id, 'panelist', 4 FROM agenda_sessions s, agenda_speakers sp WHERE s.external_ref = 'Panel 3' AND sp.slug = 'deepak-vatsa';
INSERT IGNORE INTO agenda_session_speakers (session_id, speaker_id, speaker_role, sort_order) SELECT s.id, sp.id, 'panelist', 1 FROM agenda_sessions s, agenda_speakers sp WHERE s.external_ref = 'Panel 4' AND sp.slug = 'ca-bharat-jeswani';
INSERT IGNORE INTO agenda_session_speakers (session_id, speaker_id, speaker_role, sort_order) SELECT s.id, sp.id, 'panelist', 2 FROM agenda_sessions s, agenda_speakers sp WHERE s.external_ref = 'Panel 4' AND sp.slug = 'ca-durgesh-pandey';
INSERT IGNORE INTO agenda_session_speakers (session_id, speaker_id, speaker_role, sort_order) SELECT s.id, sp.id, 'moderator', 3 FROM agenda_sessions s, agenda_speakers sp WHERE s.external_ref = 'Panel 4' AND sp.slug = 'ca-uday-kulkarni';
INSERT IGNORE INTO agenda_session_speakers (session_id, speaker_id, speaker_role, sort_order) SELECT s.id, sp.id, 'panelist', 4 FROM agenda_sessions s, agenda_speakers sp WHERE s.external_ref = 'Panel 4' AND sp.slug = 'mr-gyan-barah';
INSERT IGNORE INTO agenda_session_speakers (session_id, speaker_id, speaker_role, sort_order) SELECT s.id, sp.id, 'panelist', 5 FROM agenda_sessions s, agenda_speakers sp WHERE s.external_ref = 'Panel 4' AND sp.slug = 'soham-shah';
INSERT IGNORE INTO agenda_session_speakers (session_id, speaker_id, speaker_role, sort_order) SELECT s.id, sp.id, 'moderator', 6 FROM agenda_sessions s, agenda_speakers sp WHERE s.external_ref = 'Panel 4' AND sp.slug = 'dubashish';
INSERT IGNORE INTO agenda_session_speakers (session_id, speaker_id, speaker_role, sort_order) SELECT s.id, sp.id, 'panelist', 1 FROM agenda_sessions s, agenda_speakers sp WHERE s.external_ref = 'Panel 5' AND sp.slug = 'aman-bandvi';
INSERT IGNORE INTO agenda_session_speakers (session_id, speaker_id, speaker_role, sort_order) SELECT s.id, sp.id, 'panelist', 2 FROM agenda_sessions s, agenda_speakers sp WHERE s.external_ref = 'Panel 5' AND sp.slug = 'piyush-kaushik';
INSERT IGNORE INTO agenda_session_speakers (session_id, speaker_id, speaker_role, sort_order) SELECT s.id, sp.id, 'panelist', 3 FROM agenda_sessions s, agenda_speakers sp WHERE s.external_ref = 'Panel 5' AND sp.slug = 'mfilterit';
INSERT IGNORE INTO agenda_session_speakers (session_id, speaker_id, speaker_role, sort_order) SELECT s.id, sp.id, 'panelist', 1 FROM agenda_sessions s, agenda_speakers sp WHERE s.external_ref = 'Panel 6' AND sp.slug = 'jignesh-suba';
INSERT IGNORE INTO agenda_session_speakers (session_id, speaker_id, speaker_role, sort_order) SELECT s.id, sp.id, 'panelist', 2 FROM agenda_sessions s, agenda_speakers sp WHERE s.external_ref = 'Panel 6' AND sp.slug = 'abhinav-saurabh';
INSERT IGNORE INTO agenda_session_speakers (session_id, speaker_id, speaker_role, sort_order) SELECT s.id, sp.id, 'panelist', 3 FROM agenda_sessions s, agenda_speakers sp WHERE s.external_ref = 'Panel 6' AND sp.slug = 'alok-gupta';
INSERT IGNORE INTO agenda_session_speakers (session_id, speaker_id, speaker_role, sort_order) SELECT s.id, sp.id, 'panelist', 4 FROM agenda_sessions s, agenda_speakers sp WHERE s.external_ref = 'Panel 6' AND sp.slug = 'starlight';
INSERT IGNORE INTO agenda_session_speakers (session_id, speaker_id, speaker_role, sort_order) SELECT s.id, sp.id, 'panelist', 5 FROM agenda_sessions s, agenda_speakers sp WHERE s.external_ref = 'Panel 6' AND sp.slug = 'innefu';
INSERT IGNORE INTO agenda_session_speakers (session_id, speaker_id, speaker_role, sort_order) SELECT s.id, sp.id, 'panelist', 1 FROM agenda_sessions s, agenda_speakers sp WHERE s.external_ref = 'Panel 7' AND sp.slug = 'kumar-aniket';
INSERT IGNORE INTO agenda_session_speakers (session_id, speaker_id, speaker_role, sort_order) SELECT s.id, sp.id, 'panelist', 2 FROM agenda_sessions s, agenda_speakers sp WHERE s.external_ref = 'Panel 7' AND sp.slug = 'sainath-volam';
INSERT IGNORE INTO agenda_session_speakers (session_id, speaker_id, speaker_role, sort_order) SELECT s.id, sp.id, 'panelist', 3 FROM agenda_sessions s, agenda_speakers sp WHERE s.external_ref = 'Panel 7' AND sp.slug = 'ajay-kanth-abc';
INSERT IGNORE INTO agenda_session_speakers (session_id, speaker_id, speaker_role, sort_order) SELECT s.id, sp.id, 'panelist', 4 FROM agenda_sessions s, agenda_speakers sp WHERE s.external_ref = 'Panel 7' AND sp.slug = 'dr-navaneethan-m';
INSERT IGNORE INTO agenda_session_speakers (session_id, speaker_id, speaker_role, sort_order) SELECT s.id, sp.id, 'panelist', 5 FROM agenda_sessions s, agenda_speakers sp WHERE s.external_ref = 'Panel 7' AND sp.slug = 'sanjay-kaushik';
INSERT IGNORE INTO agenda_session_speakers (session_id, speaker_id, speaker_role, sort_order) SELECT s.id, sp.id, 'panelist', 6 FROM agenda_sessions s, agenda_speakers sp WHERE s.external_ref = 'Panel 7' AND sp.slug = 'bharat-panchal';
INSERT IGNORE INTO agenda_session_speakers (session_id, speaker_id, speaker_role, sort_order) SELECT s.id, sp.id, 'panelist', 1 FROM agenda_sessions s, agenda_speakers sp WHERE s.external_ref = 'Panel 8' AND sp.slug = 'major-general-dr-rajan-kochhar-vsm';
INSERT IGNORE INTO agenda_session_speakers (session_id, speaker_id, speaker_role, sort_order) SELECT s.id, sp.id, 'panelist', 2 FROM agenda_sessions s, agenda_speakers sp WHERE s.external_ref = 'Panel 8' AND sp.slug = 'gulshan-rai';
INSERT IGNORE INTO agenda_session_speakers (session_id, speaker_id, speaker_role, sort_order) SELECT s.id, sp.id, 'panelist', 3 FROM agenda_sessions s, agenda_speakers sp WHERE s.external_ref = 'Panel 8' AND sp.slug = 'rakesh-maheshwari';
INSERT IGNORE INTO agenda_session_speakers (session_id, speaker_id, speaker_role, sort_order) SELECT s.id, sp.id, 'panelist', 4 FROM agenda_sessions s, agenda_speakers sp WHERE s.external_ref = 'Panel 8' AND sp.slug = 'arun-kumar';
INSERT IGNORE INTO agenda_session_speakers (session_id, speaker_id, speaker_role, sort_order) SELECT s.id, sp.id, 'panelist', 5 FROM agenda_sessions s, agenda_speakers sp WHERE s.external_ref = 'Panel 8' AND sp.slug = 'amit-sharma-drdo';
INSERT IGNORE INTO agenda_session_speakers (session_id, speaker_id, speaker_role, sort_order) SELECT s.id, sp.id, 'panelist', 6 FROM agenda_sessions s, agenda_speakers sp WHERE s.external_ref = 'Panel 8' AND sp.slug = 'devesh-vatsa';
INSERT IGNORE INTO agenda_session_speakers (session_id, speaker_id, speaker_role, sort_order) SELECT s.id, sp.id, 'panelist', 1 FROM agenda_sessions s, agenda_speakers sp WHERE s.external_ref = 'Panel 9' AND sp.slug = 'balaji-kapsikar';
INSERT IGNORE INTO agenda_session_speakers (session_id, speaker_id, speaker_role, sort_order) SELECT s.id, sp.id, 'panelist', 2 FROM agenda_sessions s, agenda_speakers sp WHERE s.external_ref = 'Panel 9' AND sp.slug = 'utsav-mittal';
INSERT IGNORE INTO agenda_session_speakers (session_id, speaker_id, speaker_role, sort_order) SELECT s.id, sp.id, 'panelist', 3 FROM agenda_sessions s, agenda_speakers sp WHERE s.external_ref = 'Panel 9' AND sp.slug = 'qnu-labs';
INSERT IGNORE INTO agenda_session_speakers (session_id, speaker_id, speaker_role, sort_order) SELECT s.id, sp.id, 'panelist', 4 FROM agenda_sessions s, agenda_speakers sp WHERE s.external_ref = 'Panel 9' AND sp.slug = 'amit-dubey';
INSERT IGNORE INTO agenda_session_speakers (session_id, speaker_id, speaker_role, sort_order) SELECT s.id, sp.id, 'panelist', 1 FROM agenda_sessions s, agenda_speakers sp WHERE s.external_ref = 'Panel 10' AND sp.slug = 'smith-company';
INSERT IGNORE INTO agenda_session_speakers (session_id, speaker_id, speaker_role, sort_order) SELECT s.id, sp.id, 'panelist', 1 FROM agenda_sessions s, agenda_speakers sp WHERE s.external_ref = 'Panel 11' AND sp.slug = 'ms-paakhhi-garg';
INSERT IGNORE INTO agenda_session_speakers (session_id, speaker_id, speaker_role, sort_order) SELECT s.id, sp.id, 'panelist', 2 FROM agenda_sessions s, agenda_speakers sp WHERE s.external_ref = 'Panel 11' AND sp.slug = 'ms-garima-goswamy';
INSERT IGNORE INTO agenda_session_speakers (session_id, speaker_id, speaker_role, sort_order) SELECT s.id, sp.id, 'panelist', 3 FROM agenda_sessions s, agenda_speakers sp WHERE s.external_ref = 'Panel 11' AND sp.slug = 'sampurna';
INSERT IGNORE INTO agenda_session_speakers (session_id, speaker_id, speaker_role, sort_order) SELECT s.id, sp.id, 'panelist', 4 FROM agenda_sessions s, agenda_speakers sp WHERE s.external_ref = 'Panel 11' AND sp.slug = 'tanmayee-tilekar';
INSERT IGNORE INTO agenda_session_speakers (session_id, speaker_id, speaker_role, sort_order) SELECT s.id, sp.id, 'panelist', 5 FROM agenda_sessions s, agenda_speakers sp WHERE s.external_ref = 'Panel 11' AND sp.slug = 'smita-mitra';
INSERT IGNORE INTO agenda_session_speakers (session_id, speaker_id, speaker_role, sort_order) SELECT s.id, sp.id, 'panelist', 6 FROM agenda_sessions s, agenda_speakers sp WHERE s.external_ref = 'Panel 11' AND sp.slug = 'shonal-d';
INSERT IGNORE INTO agenda_session_speakers (session_id, speaker_id, speaker_role, sort_order) SELECT s.id, sp.id, 'panelist', 1 FROM agenda_sessions s, agenda_speakers sp WHERE s.external_ref = 'Panel 12' AND sp.slug = 'mimansa-ambastha';
INSERT IGNORE INTO agenda_session_speakers (session_id, speaker_id, speaker_role, sort_order) SELECT s.id, sp.id, 'panelist', 2 FROM agenda_sessions s, agenda_speakers sp WHERE s.external_ref = 'Panel 12' AND sp.slug = 'mr-divyam-aggarwal';
INSERT IGNORE INTO agenda_session_speakers (session_id, speaker_id, speaker_role, sort_order) SELECT s.id, sp.id, 'panelist', 3 FROM agenda_sessions s, agenda_speakers sp WHERE s.external_ref = 'Panel 12' AND sp.slug = 'suditi-tandon';
INSERT IGNORE INTO agenda_session_speakers (session_id, speaker_id, speaker_role, sort_order) SELECT s.id, sp.id, 'panelist', 4 FROM agenda_sessions s, agenda_speakers sp WHERE s.external_ref = 'Panel 12' AND sp.slug = 'mahak-rathee';
INSERT IGNORE INTO agenda_session_speakers (session_id, speaker_id, speaker_role, sort_order) SELECT s.id, sp.id, 'panelist', 5 FROM agenda_sessions s, agenda_speakers sp WHERE s.external_ref = 'Panel 12' AND sp.slug = 'krishan-kumar';
INSERT IGNORE INTO agenda_session_speakers (session_id, speaker_id, speaker_role, sort_order) SELECT s.id, sp.id, 'panelist', 6 FROM agenda_sessions s, agenda_speakers sp WHERE s.external_ref = 'Panel 12' AND sp.slug = 'vibhav-mittal';
INSERT IGNORE INTO agenda_session_speakers (session_id, speaker_id, speaker_role, sort_order) SELECT s.id, sp.id, 'panelist', 1 FROM agenda_sessions s, agenda_speakers sp WHERE s.external_ref = 'Panel 13' AND sp.slug = 'kulbhhushan-upadhyay';

COMMIT;
